
SHOW DATABASES;

USE LIVRARIA;
-- ----------[LIVROS POR CATEGORIA]-----------------------------

SELECT CATEGORIA.GENERO, LIVRO.NOME_LIVRO,LIVRARIA.NOME FROM LIVRO JOIN CATEGORIA
 ON LIVRO.CATEGORIA_ID_CATEGORIA = CATEGORIA.ID_CATEGORIA
 JOIN LIVRARIA;
-- ------------------------------------------------------------
-- -----------[ COMPRA POR MÊS ] ----------------

SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '01';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '02';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '03';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '04';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '05';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '06';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '07';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '08';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '09';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '10';
SELECT COUNT(LIVROS) FROM COMPRA WHERE  MONTH(COMPRA.DATA_COMPRA) = '11';


-- -----------[ACIMA DE 500] -----------------------------
 SELECT total_compra FROM total_compra WHERE TOTAL_COMPRA > 500;
-- ---------------------------------------------------------------













